In [1]:
import pandas as pd

df = pd.read_csv("../data/zomato_reviews.csv")

df.head()

   Unnamed: 0  rating                                             review
0           0       5                                               nice
1           1       5  best biryani , so supportive staff of outlet ,...
2           2       4     delivery boy was very decent and supportive.👌👍
3           3       1  worst biryani i have tasted in my life, half o...
4           4       5  all food is good and tasty . will order again ...

In [2]:
df.shape

(5479, 3)

In [3]:
df.columns

Index(['Unnamed: 0', 'rating', 'review'], dtype='str')

In [4]:
df.isnull().sum()

Unnamed: 0    0
rating        0
review        1
dtype: int64

In [5]:
df["review"].sample(10)

5365    Waste of money to buy from this restaurant tas...
3231                           kulcha should be cook well
2086                      this is not the cake i ordered
2744     really bad taste and mutton is not proper cooked
1484                              Bhot late delivery huva
169                       size of both item is very less
4033    Enjoyed the dinner from Mysore Express Restaur...
2838                                                nice
2558    Quantity of the food is very less. I ordered f...
1778                                               Refund
Name: review, dtype: str

In [6]:
def sentiment_label(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

In [7]:
df["sentiment"] = df["rating"].apply(sentiment_label)

In [8]:
df.head()

,Unnamed: 0,rating,review,sentiment
0,0,5,nice,Positive
1,1,5,"best biryani , so supportive staff of outlet ,...",Positive
2,2,4,delivery boy was very decent and supportive.👌👍,Positive
3,3,1,"worst biryani i have tasted in my life, half o...",Negative
4,4,5,all food is good and tasty . will order again ...,Positive